### ISSUE TITLE
Support Transcripts and Captions

### ISSUE THREAD

**Issue by mbertrand** [mitodl/odl-video-service#10]
Transcripts of videos are useful for users who like to read along with the video and are essential for users who are deaf or hard of hearing. We need to support collection admins uploading transcript file(s), users downloading transcript file(s) and playback of transcripts in time with the video. 

### Necessary functionality:
- A user should be able to upload a caption file (in VTT format) and associate it with a video
- If a video has a caption file available, the front-end player should allow the user to toggle it on/off

### acceptance criteria:
- [x] #216 Create VideoTranscript model
- [x] #217  VideoTranscript upload API
- [x] #218  add VideoTranscript object to VideoDetail API
- [x] #219 Add text track(s) to VideoJS React component
- [x] #220  Allow upload/delete of VideoTranscript from video editDialog widget
- [x] #221 add transcript download link to video detail page

### out of scope:

The current TechTV supports video captions as follows: the captioning content "is stored in S3:/techtv_static/<etag>/captions/, using the full filename and contents of an uploaded .SRT file. TechTV's default is to display closed captions whenever present: they can be disabled by clicking on "CC" on the video's lower right."

**Comment by mbertrand** [comment]
### Necessary functionality:
- A user should be able to upload a caption file (in VTT format) and associate it with a video
- If a video has a caption file available, the front-end player should allow the user to toggle it on/off

#### Backend:
- Create a `VideoCaption` model, similar to `VideoThumbnail` and `VideoFile`.
  - Fields: `video_id`, `s3_key`, `language`
  - The relation between Video and VideoCaption will be one-to-many (just in case multiple language support is added in the future).
  - Assumption is that the caption files will be stored in S3 like the thumbnails and videofiles, and will have their own bucket.  
- Create an API view (and celery task?) that will handle uploading of the files to S3 and creation of VideoCaption objects. 
  - Only support VTT files? Or also allow upload of SRT files and use python to convert them to VTT?
- The Video detail API response should include the VideoCaption objects if they exist.


#### Frontend:
- The VideoJS React player needs to be modified so that it will add a `<track>` element for each available caption file: http://docs.videojs.com/docs/guides/text-tracks.html
- The USwitch player doesn't support captions yet at all, but once it does, then it will also need to be modified to incorporate the captions.
- The edit widget for videos should be modified to allow the user to upload captions or delete existing captions.

**Comment by pdpinch** [comment]
I spoke with Matt and we can answer the questions above: 
- VTT only (at least to start)
- no need for celery, since these files are relatively small

**Comment by pdpinch** [comment]
I updated the description to better match with Matt's comment above and with the issues in the epic.

**Comment by pdpinch** [comment]
@mbertrand can this be closed? I checked off all the boxes.
