### ISSUE TITLE
Epic: Production Deployment

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#138]
## "Production readiness" checklist (based off of [MIT ODL handbook](https://github.com/mitodl/handbook/blob/master/production-ready.md))

- [x] finalized DNS names
- [x] Google analytics
- [ ] document decision to use Heroku, ec2 or Heroku/ec2 hybrid
- [x] deploy current code to production system
- [ ] document production deployment process (if not automated)
- [ ] Performance Monitoring?
- [x] Production error monitoring (Sentry)
- [ ] Mail Monitoring
- [ ] ~~Load Testing (?)~~

### Required features:
- [x] Does it support configuration via environment variables?
- [x] Does it support configuration via flatfile (e.g. YAML)?
- [ ] Does it have a sane default configuration (e.g. as close to a realistic production configuration as possible)?
- [x] Does it run on parallel HTTP workers? (e.g. uWSGI, Gunicorn)?
- [ ] Does it log to standard out/error?
- [ ] Does it log to syslog?
- [ ] Can it send stack trace emails to a configurable email list?
- [x] Does it have configurable log levels (e.g. DEBUG, ERROR, WARNING, INFO)?
- [x] Does it have a test suite which measures code coverage?
- [ ] Does it have a status route (which requires a secret token) that can be used for health checking by a monitoring service?
- [ ] Does the health check validate that each service the app depends on is reachable (e.g. databases, caching, external APIs when necessary)?
- [ ] Does the health check return a response body with the availability information above in a machine-readable format in all cases?
- [ ] Does the health check return a 500 status code when any component in the health check is detected to be failing?

### Required documentation/service infrastructure:
- [x] Does it have continuous integration builds which run the full test suite?
- [x] Does it have an automated continuous delivery to a development environment?
- [ ] Does it have a documented release process?
- [ ] Does it's release process include staging and production builds, where staging builds are promoted to production?
- [ ] Does it's release process require that code changes be "signed off" as working on staging before being promoted to production?
- [ ] Does it have application/resource monitoring in production (e.g. New Relic agent, Zenoss SNMP)?
- [ ] Does it have service availability monitoring in production (e.g. periodic health checks with Zenoss or New Relic)?
- [ ] Does it have automated, periodically generated, fully restorable backups for each non-ephemeral data store in production?

**Comment by pdpinch** [comment]
@shaidar @blarghmatey can you guys take a look at this and add/remove some details

I thought #6 would be part of this, but it's apparently already closed.

**Comment by pdpinch** [comment]
Also, after you edit this list, it would be great if you could update https://github.com/mitodl/handbook/blob/master/production-ready.md

**Comment by pdpinch** [comment]
@mitodl/devops Now that we're in de facto production, this epic needs an update. Anything that we need to do but haven't done should get a new issue.

**Comment by pdpinch** [comment]
@shaidar I checked off the Google Analytics box. Can you see what else remains to be done here?
