### ISSUE TITLE
Upload video files

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#18]
As a user I need to upload files from dropbox to the video service. 

### acceptance criteria:

- [x] upload needs to be asynchronous and not dependent on the current browser session, because they can take a long time
- [x] uploading must be robust
  - [x] we should retry if it fails
  - [x] if it fails repeatedly, the user needs to know and devops needs to know 
  - [x] if it fails repeatedly, devops needs to know
  - [x] the file on S3 should be the exact copy of the file on dropbox
- [x] avoid collisions: the users should be allowed to upload the same video multiple times having multiple instances of the same video both on Amazon and in the Portal

### Questions:

- [x] Can we ensure that the files are actually video files? (how hard do we need to try?)
- [x] What happens / what do we do if files are too large for dropbox?

**Comment by mbertrand** [comment]
> Can we ensure that the files are actually video files? (how hard do we need to try?)

I had some luck using the python-magic module to do this yesterday, it could tell the difference between a real mp4 file and a text file that I renamed with an .mp4 extension.  But I doubt it's 100% foolproof. Maybe we could do some basic validation, but if a bad/corrupt file still gets through that the transcoding will fail, and we could notify the user with a message similar to that used by Youtube: "The video has failed to process. Please make sure you are uploading a supported file type."

>What happens / what do we do if files are too large for dropbox?

20 GB is the current dropbox limit.  Youtube handles direct browser uploads of up to 128 GB (if finished < 12 hours), so maybe we could try to emulate that, or have them send us the video via FTP/SD-card and then we use a script to process it.

**Comment by Ferdi** [comment]
I think what I was talking about is basically this part of the code https://goo.gl/aKPn9E

Can we do a review about what that code and see what best practices are for uploading / streaming to S3. For example, we we are concerned about large files can we do something like this https://goo.gl/aMRmL2 and/or use parallel upload in some way ?

**Comment by mbertrand** [comment]
Sure, a code review sounds good.

Once a video file reaches the web server, it will be uploaded to S3 with the [Bucket.file_upload_obj](http://boto3.readthedocs.io/en/latest/reference/services/s3.html#S3.Bucket.upload_fileobj) method which uses multiple threads "if necessary" depending on the transfer configuration.  

But first the file needs to get to the web server.  If it is too big to fit on Dropbox, there are Javascript libraries that could be used to upload them direct through the browser in parallel chunks, for example this one: https://github.com/23/resumable.js

**Comment by giocalitri** [comment]
I made some research  and I'll comment step by step (for the items currently in the epic description).

- _upload needs to be asynchronous and not dependent on the current browser session, because they can take a long time_
  - I think that this is the implementation of the prototype that uses celery to perform the uploads.

- _uploading must be robust_
  - _we should retry if it fails_
    - considering that the web application and the celery tasks will live on EC2, the only risky part is the download of the file from dropbox, but I doubt that there will be huge issues. We should consider to put in place at least a delayed retry, but I would not go too far from there.
  - _if it fails repeatedly, the user needs to know and devops needs to know_ 
    - we can use different approaches according to what are the product requirements
  - _if it fails repeatedly, devops needs to know_
    - this should be fairly easy to implement using notifications
  - _the file on S3 should be the exact copy of the file on dropbox_
    - I introduced this point because I think that ensuring that there were not file corruptions is part of a robust upload. This is doable using the [features in dropbox](https://www.dropbox.com/developers/reference/content-hash) and the [ones in S3](https://aws.amazon.com/premiumsupport/knowledge-center/data-integrity-s3/).
- _avoid collisions: the users should be allowed to upload the same video multiple times having multiple instances of the same video both on Amazon and in the Portal_
  - we should probably just create a unique name for each file upload session


### Questions:

- _Can we ensure that the files are actually video files? (how hard do we need to try?)_
  - Yes (see [python-magic](https://github.com/ahupp/python-magic))
- _What happens / what do we do if files are too large for dropbox?_
  - There should not be such a thing as file too large for dropbox (see [documentation](https://www.dropbox.com/help/space/upload-limitations))

**Comment by pdpinch** [comment]
@mbertrand @giocalitri can we close this epic now? I can live without #22 "Verify that files chosen from Dropbox are really video files" since non-video files will fail transcoding.

**Comment by mbertrand** [comment]
okay with me, though I'm working on a PR that addresses failure-handling which is somewhat relevant to this.

**Comment by pdpinch** [comment]
Is that #50? I thought that was about handling transcode failures?

**Comment by mbertrand** [comment]
It addresses upload failures too (primarily via status updates).
