### ISSUE TITLE
transcoding video files

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#19]
As a user, I want to upload video files in any format and have them converted to formats suitable for streaming. 

### acceptance criteria

- [x] #3 asynchronous process, since it can take some time
- [x] #3 user needs to see status in app (done, in progress, failure)
- [x] #23 retry on failures
- [x] #24 devops needs to be alerted on repeated failures
- [x] #3 need to choose output formats based on front-end requirements
- [x] #3 video output formats should be configurable at the application level
- [x] #77 choose transcode presets

### questions

- [x] Is HLS sufficient, or do we still need multiple, individual bit rates?
  - HLS on AWS Cloudfront requires multiple individual files

### nice to have

- [x] notify user (email) when transcode is complete

**Comment by mbertrand** [comment]
> need to choose output formats based on front-end requirements
> video output formats should be configurable

My assumption was that all videos would be transcoded the same way using the same presets, and at most the user could choose to play back the video in the player at different resolutions like 360P vs HD, but the default would be for the browser to choose the best resolution based on the client's bandwidth.

>Is HLS sufficient, or do we still need multiple, individual bit rates?

Based on the example I walked through, multiple bit rates are still generated, but HLS has a 'master playlist' file that links to the different encodings to allow for adaptive streaming: https://www.jwplayer.com/blog/encoding-hls-with-amazon-elastic-transcoder/

**Comment by pdpinch** [comment]
Sorry, I wasn't clear about "configurable." I want the same transcode settings for the entire app, but I'd like a way to be able to change those settings if we need to at some point in the future. I updated the description to specify "configurable at the application level".

I removed the question about HLS. It appears that cloudfront only supports the HLS configuration where a manifest file points to multiple files in different bitrates.

**Comment by rhysyngsun** [comment]
Reopening because #23 and #24 are still open.

**Comment by pdpinch** [comment]
This seems done to me

**Comment by emmello** [comment]
Do you want to limit what formats can be uploaded?  This was a question with TechTV because of issues with filesizes - m4vs, ProRes formats, etc.

**Comment by pdpinch** [comment]
I think we're taking a pragmatic approach: if AWS can transcode it, we'll take it. 

If it can't transcode it, we'll return an error to the user.

**Comment by emmello** [comment]
Sounds good.  Some of the issues may have been with the custom transcode for TechTV, so probably doesn't apply with Elastic Transcode.
