### ISSUE TITLE
simple video playback

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#20]
As a video creator, I need to be able to stream my videos

### requirements

- [x] Choose video player: recommend Video.js or AblePlayer
- [x] Create HTML template that embeds video player
- [x] HTML page requires authentication
  - [ ] link to signed Cloudfront URL for video stream
- [ ] must work in mobile (iOS, Android) 
- [ ] subtitle support 

### nice to have

- [ ] chapter support

**Comment by mbertrand** [comment]
Video Player:
- AblePlayer does not support HLS so it is out.
- VideoJS supports HLS and subtitles, BUT:
   - subtitles must be in vtt format not srt (python can be used to convert)
   - the HLS plugin is a bit flaky (compatibility issues with webpack; also encoding issues described below).
  - Supposedly works in mobile but not yet tested

Authentication:
- It is possible to generate a signed Cloudfront URL to the HLS playlist file. However, the playlist contains links to the different bitrate video files, and those links will not be signed.  Therefore, if the Cloudfront distribution is set up to require signed URL's, the playlist will be loaded but the video will not be able to play.  Flowplayer exhibits the same behavior.  Some other options:
  - Use signed cookies instead of URL's.  This will require registering a CNAME to the cloudfront distribution of <something>.odl.mit.edu so that cookies can be sent to cloudfront from the production app.  Theoretically this will work but hard to know without testing.
  - Use encrypted HLS.  I experimented with this using VideoJS and unfortunately it only plays part of the video and finishes prematurely.  Tried with Flowplayer and it wouldnt play at all. 
  - Store the original playlist(s) in the app, and when the video is requested, create a copy with new signed URL's for each link and send that to the page instead. Question: will an HLS playlist with absolute URL's work (default is relative)?

**Comment by mbertrand** [comment]
- Subtitles are supported by video.js but code for uploading/adding them still needs to be added to the app.  Chapters supported by videojs too.  Example with both [here](http://www.aa.org/js/video-js/examples/elephantsdream/).

- I think signed cookies instead of signed url's are probably the best security solution.

**Comment by pdpinch** [comment]
@mbertrand @giocalitri can we close this now that #40 is merged?

**Comment by mbertrand** [comment]
@pdpinch Although videojs does claim to support mobile playback, I haven't verified that it does work yet, and subtitle support is not yet integrated into the app, but if that's okay then I'm fine with closing it now.

**Comment by pdpinch** [comment]
Let's leave this open until we can verify mobile playback. 

This story only requires that subtitles are possible, not that they are implemented in the app. We'll open another issue for that once we have a better idea of how we want subtitles to function.

**Comment by pdpinch** [comment]
I took a look in iOS. As with Android, the player controls need to be styled/sized, but otherwise it looked good. In particular, going to full screen behaved as expected. 

I think we can close this and move on to other player issues next sprint.
