### ISSUE TITLE
Public Videos

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#334]
Some ODL partners would like to stream their video publicly (i.e. without login requirements) but, due to access restrictions, can't rely on typical public streaming services like YouTube. 

### acceptance criteria

- [x] Video player fails over to Cloudfront when YouTube is blocked or video is unavailable on YouTube
- [x] Allow collection admin to specify that video is public
- [x] Allow unauthenticated access to view and embed pages for public videos
- [x] push public videos to YouTube
- [x] stream public videos from YouTube first, when available. 
- [x] remove videos from YouTube when they go private or are deleted

### out of scope
- Allow collection admin to specify that collection is public
- allow unauthenticated access to collection page

**Comment by pdpinch** [comment]
I edited some of the requirements based on our decision to use YouTube when available, but otherwise stream from Cloudfront. 

And with that, this epic is complete.
