### ISSUE TITLE
Migrate TechTV Protected Collections to OVS

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#408]
This epic is part of a larger effort to shut down the TechTV web site. 

Protected collections on TechTV will be relatively easy to migrate to OVS because they have similar permission settings to OVS private collections. Protected collections, and the videos within them, can only be viewed by their owners and members of associated moira lists. In the migration, we want to maintain existing URLs for collections, for video detail pages, for embedded videos and, to the extent possible, streams. We will not transcode videos. We will convert caption files. 

### Acceptance criteria
- [x] separate s3 ~~bucket~~ subfolders for migrated techtv videos, captions and thumbnails
- [x] modify OVS video player to handle TechTV's mp4 video, avoiding transcoding videos
- [x] create user accounts for collection owners as necessary (but not for non-MIT accounts)
- [x] migrate moira lists for collection admins and collection viewers (don't migrate TechTV's moira lists for upload permission)
- [x] migrate collection and video metadata only for fields that exist in OVS: title, description (other TechTV metadata will be preserved for future use)
- [x] don't migrate videos objects where the video has been lost
- [x] migrate caption files from TechTV local storage to OVS S3 bucket. 
- [x] ~~transform captions from SRT to VTT~~
- [x] migrate thumbnails 
- [x] set up nginx sever to redirect TechTV routes to OVS routes (lost videos will 404)
- [x] deploy the code and perform the migration

### not part of this epic
- public collections
- change DNS

**Comment by Ferdi** [comment]
> create user accounts for collection owners as necessary (including non-MIT accounts)

I thought we'd not create account for non-MIT users. Instead , make @emmello the owner.  Is that right ?

**Comment by mbertrand** [comment]
Some initial thoughts on how to implement the migration process:
 - Develop as Django ETL commands with Bonobo (thanks @blarghmatey for the suggestion): http://docs.bonobo-project.org/en/latest/extension/django.html#bonobo.contrib.django.ETLCommand
-  copy over all S3 files first (videos, thumbnails, and captions) from old buckets to new buckets
-  for each SRT caption file found in S3, convert to VTT if possible and upload to the same bucket, same S3 key but with a different extension (#416)
-  for each S3 bucket prefix specific to a video (such as `044bc0080f75ac15c6129816c517ccfa`), create the required `Video` object and associated objects (`Collection`, `User` (#414), `VideoFile`, `VideoThumbnail` (#417), `VideoSubtitle` (#416) - more details will be provided in #415
  - Any videos, users, collections in the MySQL database with video files that no longer exist in S3 won't be created in OVS.

**Comment by pdpinch** [comment]
@mbertrand can you update the checkboxes in the issue description?

**Comment by pdpinch** [comment]
@emmello @mbertrand do you think this we close this epic, for migrating protected collections?

**Comment by emmello** [comment]
Is there any way we can test the redirects yet?

**Comment by mbertrand** [comment]
@emello for any video that's been imported, the TechTV URL with the domain replaced by 'video.odl.mit.edu', should still work, for example:
https://video.odl.mit.edu/videos/26106-machine-learning-oct-7-2013
https://video.odl.mit.edu/embeds/26106
https://video.odl.mit.edu/videos/c959019eeebbeb5c33760fc7325da4eb1935be5a/private

**Comment by emmello** [comment]
Right, but if I go to the TechTV link, will it now redirect to the OVS, or does that work still need to happen?

**Comment by mbertrand** [comment]
That still needs to happen (after all collections/videos have been imported)

**Comment by pdpinch** [comment]
We can test these URLs locally by modifying /etc/hosts (assuming that ovs is configured to respond to requests for techtv.mit.edu -- @mitodl/devops ?)

**Comment by pdpinch** [comment]
We can test these URLs locally by modifying /etc/hosts (assuming that ovs is configured to respond to requests for techtv.mit.edu -- @mitodl/devops ?)

**Comment by pdpinch** [comment]
@emmello and @mbertrand is this done, in production?

Am I correct in thinking that the only thing we need to do for protected collections is #440 ?

**Comment by emmello** [comment]
I believe all protected collections were already ported over.

**Comment by mbertrand** [comment]
Yes, all protected collections were imported.
