### ISSUE TITLE
map TechTV routes to OVS routes

### ISSUE THREAD

**Issue by pdpinch** [mitodl/odl-video-service#418]
This needs some more detailed description, probably with some interim steps, e.g. 

- [x] map protected TechTV URLs to private OVS URLs
- [ ] ~~map public TechTV embed URLs to corresponding YouTube URLs~~
- [x] map lost TechTV URLs to 404
- [x] update nginx so OVS can respond to TechTV requests
- [ ] update TechTV DNS to point to OVS application

### questions
- Should the mapping be static, and handled by nginx? Or should the routes be mapped to django views which then handle the mapping? **answer: handled by django**
- Should we return 301 to a new URL, or respond at the old URL with new content? **answer: URLs will remain as is with TechTV domain**

**Comment by emmello** [comment]
Videos on TechTV which are Protected will have a 1 in the database collection in the Protected column of the database.  

example:  [http://techtv.mit.edu/collections/6036spring2017]   This collection has "Protected, remove production" checked off, designating this as a protected collection.    Access to this list is secured through Moira / Touchstone access.

Videos on TechTV can be designated as Private (database field Private will have a 1, and the Private_token" field will have an AWS Cloudfront hash link.   For instance, this video is on TechTV:

http://techtv.mit.edu/videos/5014-intuitively-obvious-clips

Options in the righthand margin allow the video owner to make the video private, as well as to enable embedding and downloading.  
![image](https://user-images.githubusercontent.com/1099800/35343075-aca5bf16-00f7-11e8-9229-b0def644334c.png)

When private is selected, a link appears at the top of the video page that the owner can copy and send out to others.   This video is only secured through obscurity.  

The private link for this video would be http://techtv.mit.edu/videos/b552f7de1d65f52295e4241fe9d72834645d2297/private  

If embed is on, a user would have the ability to choose embed size (large medium small, responsive or custom) and this information is build into the iFrame code:

Embed code for this video:  

<iframe src="http://techtv.mit.edu/embeds/5014?size=medium&amp;custom_width=432&amp;external_stylesheet=" frameborder="0" width="432" height="200"></iframe>

![image](https://user-images.githubusercontent.com/1099800/35343280-4764e27a-00f8-11e8-88d6-80010099386a.png)

**Comment by pdpinch** [comment]
It looks like the slug is an option part of the path, i.e. http://techtv.mit.edu/videos/5014-intuitively-obvious-clips is the same as http://techtv.mit.edu/videos/5014

**Comment by emmello** [comment]
Yeah, the most important part is the number there - if someone renames the file, they can share that link, which is probably what happened there.

**Comment by mbertrand** [comment]
@pdpinch @emmello Private TechTV videos are set to have view permissions of 'Owner only' when imported to OVS; should anyone still be able to view it if they use the OVS private link? 

http://techtv.mit.edu/videos/eddad6b780efc0b4368b6f812a085122d213b790/private --> http://video.odl.mit.edu/videos/eddad6b780efc0b4368b6f812a085122d213b790/private

**Comment by mbertrand** [comment]
@blarghmatey I plan to have the TechTV video URL's working in OVS as is, with just the domain replaced, for example:

http://techtv.mit.edu/videos/358-measurements-demo-lecture-1 -> http://video.odl.mit.edu/videos/358-measurements-demo-lecture-1

http://techtv.mit.edu/embeds/358/ -> http://video.odl.mit.edu/embeds/358/

http://techtv.mit.edu/videos/<private_token>/private --> http://video.odl.mit.edu/videos/<private_token>/private

**Comment by mbertrand** [comment]
@pdpinch question about #2 in the description (map public TechTV embed URLs to corresponding YouTube URLs): do you want the public videos to be played from Youtube via VideoJS-Youtube plugin at an OVS URL?  The front-end code for that hasn't been finalized yet.

**Comment by pdpinch** [comment]
I'm turning this into an epic, and I'll modify PR #434 so that it's only fixes the private part.

**Comment by mbertrand** [comment]
@pdpinch @emmello I think the checkboxes could use some tweaking:

- [ ] Map TechTV URL's for videos in protected collections to moira-protected OVS URL's (`/videos/<video_id>-<slug>`)
- [ ] Map TechTV embed URL's for videos in protected collections to moira-protected OVS embed URL's (`/embeds/<video_id>`)
- [ ] Map TechTV URL's for private videos to admin-only OVS URL's (`/videos/<private_token>/private`)

**Comment by pdpinch** [comment]
Makes sense, but since this is an epic now, I copied these checkboxes to #436

**Comment by pdpinch** [comment]
This is done, although we overlooked download links (#639)
